'use client';
// Datacenter sprawl generated by Wave Function Collapse. Snappable tiles (roads
// that must connect to roads, building blocks that fill the rest) collapse into a
// coherent campus. Rendered as a glowing tech city at night. Regenerate for a new layout.
import * as THREE from 'three';
import { useMemo, useState, useRef, useEffect } from 'react';
import Link from 'next/link';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import { EffectComposer, Bloom, Vignette } from '@react-three/postprocessing';
import { generateWFC, type WfcTile } from '@/lib/wfc';
import { useChoices } from '@/lib/choices';
import { useFade } from '@/lib/useFade';
import Fader from '@/components/Fader';
import { worldMeters, MeterBars } from '@/components/WorldReport';
import { FirstPerson, WorldFigures, WorldPortals, EncounterPanel, buildField, ENCOUNTER_CSS, type Portal } from '@/components/WorldEncounter';
import PlayWorld from '@/components/PlayWorld';
import NPCs from '@/components/NPCs';

const W = 22, H = 22, TS = 1.5;
const TILES: WfcTile[] = [
  { name: 'build', sockets: ['g', 'g', 'g', 'g'], weight: 6 },
  { name: 'plaza', sockets: ['g', 'g', 'g', 'g'], weight: 1 },
  { name: 'roadH', sockets: ['g', 'r', 'g', 'r'], weight: 1.4 },
  { name: 'roadV', sockets: ['r', 'g', 'r', 'g'], weight: 1.4 },
  { name: 'roadX', sockets: ['r', 'r', 'r', 'r'], weight: 0.5 },
  { name: 'turnNE', sockets: ['r', 'r', 'g', 'g'], weight: 0.5 },
  { name: 'turnES', sockets: ['g', 'r', 'r', 'g'], weight: 0.5 },
  { name: 'turnSW', sockets: ['g', 'g', 'r', 'r'], weight: 0.5 },
  { name: 'turnWN', sockets: ['r', 'g', 'g', 'r'], weight: 0.5 },
];
function h2(x: number, y: number, s: number) { const v = Math.sin(x * 127.1 + y * 311.7 + s * 13.7) * 43758.5453; return v - Math.floor(v); }
const WIN_COLORS = ['#39e0ff', '#7fe0ff', '#bdf7ff', '#1affa0', '#ffd23a'];

function City({ grid, seed }: { grid: number[]; seed: number }) {
  const data = useMemo(() => {
    const buildings: [number, number, number][] = [], windows: [number, number, number][] = [], roads: [number, number][] = [], towers: [number, number][] = [];
    for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
      const tile = TILES[grid[y * W + x]];
      const wx = (x - W / 2) * TS, wz = (y - H / 2) * TS;
      if (tile.name.startsWith('road') || tile.name.startsWith('turn')) roads.push([wx, wz]);
      else if (tile.name === 'build') {
        const r = h2(x, y, seed);
        const ht = 0.6 + r * 2.0;
        buildings.push([wx, wz, ht]);
        windows.push([wx, wz, ht * 0.42]); windows.push([wx, wz, ht * 0.74]);
        if (r > 0.88) towers.push([wx, wz]);
      }
    }
    return { buildings, windows, roads, towers };
  }, [grid, seed]);

  const dummy = useMemo(() => new THREE.Object3D(), []);
  const buildings = useMemo(() => {
    const m = new THREE.InstancedMesh(new THREE.BoxGeometry(TS * 0.82, 1, TS * 0.82), new THREE.MeshStandardMaterial({ color: '#33455f', roughness: 0.55, metalness: 0.4, emissive: '#0c1830', emissiveIntensity: 0.25 }), Math.max(1, data.buildings.length));
    data.buildings.forEach((b, i) => { dummy.position.set(b[0], b[2] / 2, b[1]); dummy.scale.set(1, b[2], 1); dummy.rotation.set(0, 0, 0); dummy.updateMatrix(); m.setMatrixAt(i, dummy.matrix); });
    m.instanceMatrix.needsUpdate = true; m.castShadow = true; m.receiveShadow = true; return m;
  }, [data, dummy]);
  const windows = useMemo(() => {
    const m = new THREE.InstancedMesh(new THREE.BoxGeometry(TS * 0.85, 0.14, TS * 0.85), new THREE.MeshBasicMaterial({ toneMapped: false }), Math.max(1, data.windows.length));
    const col = new THREE.Color();
    data.windows.forEach((w, i) => { dummy.position.set(w[0], w[2], w[1]); dummy.scale.set(1, 1, 1); dummy.rotation.set(0, 0, 0); dummy.updateMatrix(); m.setMatrixAt(i, dummy.matrix); col.set(WIN_COLORS[(h2(w[0], w[1], i) * WIN_COLORS.length) | 0]); m.setColorAt(i, col); });
    m.instanceMatrix.needsUpdate = true; if (m.instanceColor) m.instanceColor.needsUpdate = true; return m;
  }, [data, dummy]);
  const roads = useMemo(() => {
    const m = new THREE.InstancedMesh(new THREE.BoxGeometry(TS, 0.06, TS), new THREE.MeshStandardMaterial({ color: '#0c1018', roughness: 0.9, emissive: '#0a1830', emissiveIntensity: 0.4 }), Math.max(1, data.roads.length));
    data.roads.forEach((r, i) => { dummy.position.set(r[0], 0.03, r[1]); dummy.scale.set(1, 1, 1); dummy.rotation.set(0, 0, 0); dummy.updateMatrix(); m.setMatrixAt(i, dummy.matrix); });
    m.instanceMatrix.needsUpdate = true; m.receiveShadow = true; return m;
  }, [data, dummy]);
  const towers = useMemo(() => {
    const m = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.3, 0.36, 1, 12), new THREE.MeshStandardMaterial({ color: '#28323f', roughness: 0.7, metalness: 0.4 }), Math.max(1, data.towers.length));
    data.towers.forEach((t, i) => { dummy.position.set(t[0] + 0.3, 1.2, t[1] + 0.3); dummy.scale.set(1, 2.4, 1); dummy.rotation.set(0, 0, 0); dummy.updateMatrix(); m.setMatrixAt(i, dummy.matrix); });
    m.instanceMatrix.needsUpdate = true; m.castShadow = true; return m;
  }, [data, dummy]);

  return (
    <group>
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, 0, 0]} receiveShadow>
        <planeGeometry args={[W * TS + 8, H * TS + 8]} />
        <meshStandardMaterial color="#070a12" roughness={1} />
      </mesh>
      <primitive object={buildings} />
      <primitive object={windows} />
      <primitive object={roads} />
      <primitive object={towers} />
    </group>
  );
}

function Spin() {
  useFrame((s) => { const t = s.clock.elapsedTime * 0.06; s.camera.position.set(Math.cos(t) * 36, 20 + Math.sin(t * 0.4) * 5, Math.sin(t) * 36); s.camera.lookAt(0, 1, 0); });
  return null;
}

// the people who finance, demand and supply the compute this city is built for — they
// stand along a cleared avenue you can walk down (the WFC grid is carved open here)
const PLAZA = TILES.findIndex((t) => t.name === 'plaza');
const AVENUE_ROWS = [10, 11, 12];
const CITY_FIELD = buildField([
  { node: 'OpenAI', pos: [-9, -1.2] },
  { node: 'Nvidia', pos: [0, 1.2] },
  { node: 'Microsoft', pos: [9, -1.2] },
]);
const SPAWN: [number, number, number] = [-15, 0, 0];
const CAR_SPAWN: [number, number, number] = [-12, 0, 1.5];   // on the avenue
const BOUND = (W / 2) * TS - 1;
// at the far end of the avenue, past the trio — walk through it to return to the globe
const CITY_PORTALS: Portal[] = [
  { pos: [14, 0], dest: '/world', title: 'BACK TO THE WORLD', label: 'returning to the world', color: '#39e0ff' },
];

export default function CityGenerator() {
  const [seed, setSeed] = useState(1);
  const [mode, setMode] = useState<'fly' | 'orbit' | 'walk' | 'play'>('fly');
  const [driving, setDriving] = useState(false);
  const playerPosRef = useRef(new THREE.Vector3());

  // generate the city, then carve a walkable avenue through the middle for the figures
  const grid = useMemo(() => {
    const g = generateWFC(W, H, TILES, 'city' + seed);
    for (let x = 0; x < W; x++) for (const gy of AVENUE_ROWS) g[gy * W + x] = PLAZA;
    return g;
  }, [seed]);

  const sampleRef = useRef<((x: number, z: number) => number) | null>(() => 0); // flat ground
  const blockedRef = useRef<((x: number, z: number) => boolean) | null>(null);
  useEffect(() => {
    const building = new Set<number>();
    for (let i = 0; i < grid.length; i++) if (TILES[grid[i]].name === 'build') building.add(i);
    blockedRef.current = (wx, wz) => {
      const gx = Math.round(wx / TS + W / 2), gy = Math.round(wz / TS + H / 2);
      if (gx < 0 || gy < 0 || gx >= W || gy >= H) return false;
      return building.has(gy * W + gx);
    };
  }, [grid]);

  // in-world encounters
  const [choices, setChoice] = useChoices();
  const [near, setNear] = useState(-1);
  const nearRef = useRef(-1);
  const [active, setActive] = useState(-1);
  const pausedRef = useRef(false);
  useEffect(() => { pausedRef.current = active >= 0; }, [active]);
  const walking = mode === 'walk' || mode === 'play';
  const onFootOrigin = mode === 'play' ? playerPosRef : undefined;
  const metCount = CITY_FIELD.filter((f) => choices[f.node]).length;
  const meters = worldMeters(choices);
  const { go, out: leaving, label: leaveLabel } = useFade();
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.code === 'Escape') { setActive(-1); return; }
      if (e.code === 'KeyE' && walking && active < 0 && nearRef.current >= 0) {
        setActive(nearRef.current);
        if (typeof document !== 'undefined' && document.exitPointerLock) document.exitPointerLock();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [walking, active]);

  return (
    <div className="cy-stage">
      <Canvas shadows dpr={[1, 1.5]} performance={{ min: 0.5 }} camera={{ position: [34, 22, 34], fov: 40 }}>
        <color attach="background" args={['#05080f']} />
        <fog attach="fog" args={['#05080f', 45, 95]} />
        <ambientLight intensity={0.45} />
        <hemisphereLight args={['#3a5882', '#0a0e16', 0.75]} />
        <directionalLight position={[20, 30, 14]} intensity={1.5} color="#bcd4f2" castShadow shadow-mapSize={[1024, 1024]} shadow-camera-left={-30} shadow-camera-right={30} shadow-camera-top={30} shadow-camera-bottom={-30} />
        <City grid={grid} seed={seed} />
        {(mode === 'play' || mode === 'walk') && <NPCs sampleRef={sampleRef} count={5} range={14} isWalkable={(x, z) => !blockedRef.current?.(x, z)} />}
        <WorldFigures field={CITY_FIELD} sampleRef={sampleRef} walking={walking && active < 0} choices={choices} nearRef={nearRef} setNear={setNear} radius={5} originRef={onFootOrigin} />
        <WorldPortals portals={CITY_PORTALS} sampleRef={sampleRef} walking={walking && active < 0} onEnter={(p) => go(p.dest, p.label)} originRef={onFootOrigin} />
        {mode === 'play' ? <PlayWorld sampleRef={sampleRef} pausedRef={pausedRef} posRef={playerPosRef} setDrivingUI={setDriving} blockedRef={blockedRef} spawn={SPAWN} carSpawn={CAR_SPAWN} bound={BOUND} />
          : mode === 'walk' ? <FirstPerson sampleRef={sampleRef} pausedRef={pausedRef} blockedRef={blockedRef} spawn={SPAWN} bound={BOUND} />
          : mode === 'orbit' ? <OrbitControls makeDefault enablePan={false} minDistance={18} maxDistance={80} maxPolarAngle={1.45} target={[0, 1, 0]} />
          : <Spin />}
        <EffectComposer>
          <Bloom intensity={0.7} luminanceThreshold={0.5} luminanceSmoothing={0} mipmapBlur={false} />
          <Vignette eskil={false} offset={0.25} darkness={0.9} />
        </EffectComposer>
      </Canvas>

      <div className="cy-ui">
        <div className="cy-top">
          <Link href="/world" className="cy-back">← world</Link>
          <div className="cy-title">WFC DATACENTER SPRAWL</div>
          <div className="cy-sub">Wave Function Collapse grid · walk it · meet the compute trio</div>
        </div>
        <div className="cy-panel">
          <button className="cy-seed" onClick={() => setSeed((s) => s + 1)}>↻ collapse a new city</button>
          <div className="cy-modes">
            {(['fly', 'orbit', 'walk', 'play'] as const).map((m) => (
              <button key={m} className={'cy-mode' + (mode === m ? ' on' : '')} onClick={() => setMode(m)}>{m === 'fly' ? '🎥 fly' : m === 'orbit' ? '⊙ orbit' : m === 'walk' ? '🚶 1st' : '🎮 play'}</button>
            ))}
          </div>
        </div>
      </div>

      {walking && (
        <div className="cy-quest">
          <div className="cy-quest-head">THE WORLD · LIVE STATE</div>
          <MeterBars meters={meters} />
          <div className="cy-quest-foot">{metCount === CITY_FIELD.length ? '✓ the compute trio — every call made' : `${metCount}/${CITY_FIELD.length} spoken · the demand, the capital, the chips`}</div>
        </div>
      )}
      {walking && active < 0 && near >= 0 && (
        <div className="cy-prompt"><span className="cy-key">E</span> speak with <b style={{ color: CITY_FIELD[near].fig.accent }}>{CITY_FIELD[near].enc.name}</b> — {CITY_FIELD[near].enc.role}</div>
      )}
      {active >= 0 && (
        <EncounterPanel f={CITY_FIELD[active]} prior={choices[CITY_FIELD[active].node]} onPick={(id) => setChoice(CITY_FIELD[active].node, id)} onClose={() => setActive(-1)} />
      )}
      {walking && (
        <div className="cy-walkhint">click to look · <b>WASD</b> move{mode === 'play' ? <> · <b>F</b> {driving ? 'exit car' : 'enter car'}</> : <> · <b>shift</b> run</>} · <b>esc</b> release</div>
      )}

      <Fader out={leaving} label={leaveLabel} />

      <style dangerouslySetInnerHTML={{ __html: `
        .cy-stage{position:fixed;inset:0;background:#05080f}
        .cy-ui{position:absolute;inset:0;pointer-events:none;padding:60px 28px 24px;display:flex;flex-direction:column;justify-content:space-between}
        .cy-back{pointer-events:auto;font-family:var(--font-mono);font-size:0.6rem;letter-spacing:0.1em;color:rgba(255,255,255,0.5);text-decoration:none}
        .cy-back:hover{color:#fff}
        .cy-title{font-family:var(--font-mono);font-size:0.85rem;letter-spacing:0.22em;color:#fff;margin-top:14px}
        .cy-sub{font-family:var(--font-mono);font-size:0.58rem;letter-spacing:0.05em;color:rgba(255,255,255,0.5);margin-top:5px}
        .cy-panel{pointer-events:auto;align-self:flex-start;display:flex;gap:8px;align-items:center}
        .cy-seed{font-family:var(--font-mono);font-size:0.64rem;letter-spacing:0.05em;color:#04140d;background:linear-gradient(135deg,#39e0ff,#1aa0d0);border:none;border-radius:9px;padding:11px 16px;cursor:pointer}
        .cy-modes{display:flex;gap:6px}
        .cy-mode{font-family:var(--font-mono);font-size:0.62rem;letter-spacing:0.04em;color:#fff;background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.18);border-radius:9px;padding:11px 13px;cursor:pointer;transition:all 0.18s}
        .cy-mode:hover{border-color:rgba(57,224,255,0.6)}
        .cy-mode.on{background:#39e0ff;color:#04140d;border-color:#39e0ff;font-weight:700}
        .cy-quest{position:absolute;top:90px;right:24px;z-index:6;width:240px;padding:14px 16px 12px;background:linear-gradient(160deg,rgba(20,25,44,0.85),rgba(12,15,31,0.9));border:1px solid rgba(255,255,255,0.1);border-radius:14px;backdrop-filter:blur(10px);box-shadow:0 14px 40px rgba(0,0,0,0.4)}
        .cy-quest-head{font-family:var(--font-mono);font-size:0.55rem;letter-spacing:0.18em;color:#39e0ff;margin-bottom:10px}
        .cy-quest-foot{font-family:var(--font-mono);font-size:0.55rem;letter-spacing:0.03em;color:rgba(255,255,255,0.5);margin-top:10px;padding-top:9px;border-top:1px solid rgba(255,255,255,0.08)}
        .cy-prompt{position:absolute;bottom:72px;left:50%;transform:translateX(-50%);z-index:6;pointer-events:none;font-family:var(--font-mono);font-size:0.72rem;letter-spacing:0.04em;color:#fff;background:rgba(10,16,28,0.78);border:1px solid rgba(57,224,255,0.4);border-radius:999px;padding:11px 20px;backdrop-filter:blur(8px)}
        .cy-prompt .cy-key{display:inline-grid;place-items:center;width:20px;height:20px;margin-right:9px;border-radius:5px;background:#39e0ff;color:#04140d;font-weight:700;font-size:0.66rem;vertical-align:middle}
        .cy-walkhint{position:absolute;bottom:32px;left:50%;transform:translateX(-50%);z-index:5;pointer-events:none;font-family:var(--font-mono);font-size:0.64rem;letter-spacing:0.06em;color:#fff;background:rgba(10,16,28,0.6);border:1px solid rgba(255,255,255,0.14);border-radius:999px;padding:9px 18px;backdrop-filter:blur(8px)}
        .cy-walkhint b{color:#39e0ff}
        ${ENCOUNTER_CSS}
      ` }} />
    </div>
  );
}
